
[book]
title = "Notebook"
description = "This book covers the notes from understandings."
src = "docs"
authors = ["Swapnil Mhamane"]
language = "en"
multilingual = true

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = false

#[preprocessor.toc]
#command = "mdbook-toc"

#[preprocessor.mermaid]
#command = "mdbook-mermaid"
#renderer = ["html"]

[output.html]
# theme = "my-theme"
default-theme = "light"
preferred-dark-theme = "navy"
# curly-quotes = true
# mathjax-support = true
# copy-fonts = true
# google-analytics = "UA-123456-7"
additional-css = ["vendor/mermaid.css"]
additional-js = ["vendor/mermaid.min.js" , "vendor/mermaid-init.js"]
# no-section-label = false
git-repository-url = "https://github.com/swapnilgm/notes"
# git-repository-icon = "fa-github"
# site-url = "/notes/"
# input-404 = "not-found.md"

# [output.html.fold]
# enable = false
# level = 0

# [output.html.playground]
# editable = false
# copy-js = true
# line-numbers = false

# [output.html.search]
# enable = true
# limit-results = 30
# teaser-word-count = 30
# use-boolean-and = true
# boost-title = 2
# boost-hierarchy = 1
# boost-paragraph = 1
# expand = true
# heading-split-level = 3
# copy-js = true

# [output.html.redirect]
