name: Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            mdbook
          key: ${{ runner.os }}-mdbook
      - name: Install mdbook
        run: |
          arch=$(uname -m)
          mdbookversion=v0.4.3
          mdbooktocversion=0.5.1
          echo $PATH
          curl -LsSf https://github.com/rust-lang/mdBook/releases/download/${mdbookversion}/mdbook-${mdbookversion}-${arch}-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin
          curl -LsSf https://github.com/badboy/mdbook-toc/releases/download/${mdbooktocversion}/mdbook-toc-${mdbooktocversion}-${arch}-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin
      - name: Deploy docs
        run: |
          mdbook build .
          git fetch origin gh-pages
          git worktree add /tmp/book gh-pages
          rm -rf /tmp/book/*
          cp -rp book/* /tmp/book/
          cd /tmp/book
          if [[ ! -z $(git status --porcelain) ]]; then
            git add -A
            git config --local user.email "noreply@github.com"
            git config --local user.name "${{ github.actor }}"
            git commit -m ":rocket: Deployed ${{ github.sha }} to gh-pages"
            git push origin gh-pages
          fi
          git worktree remove /tmp/book
